### ISSUE TITLE
Parameter assignement differs between declaration section and implementation section

### ISSUE THREAD

**Issue by RogerChristopher** [Barteling/STweep#21]
When a FB is initialised with parameters defined in a FB_Init methods, assignment to these parameters is not formatted in the same way as assignment to VAR_INPUT parameters in the implementation section.

See:
![Capture](https://user-images.githubusercontent.com/32986382/107123795-9b501800-6897-11eb-9409-5cad3bb3db36.PNG)

**Comment by Barteling** [comment]
Thanks for noting, i'll check it.

**Comment by Roald87** [comment]
I noticed something similar. My settings are such that I don't want a space around `:=` in function block calls and I expected it to do the same with `FB_init` parameter assignment or struct assignment. For example:

```
// in
FB POU
VAR_INPUT
    anArray : ARRAY[1..2] OF ST_Struct := (var1:=1, var2:=3);
END_VAR
VAR
    fbToCall : SomeFb;
END_VAR

fbToCall(aString:='dsfsd');

// out
FB POU
VAR_INPUT
    anArray : ARRAY[1..2] OF ST_Struct := (var1 := 1, var2 := 3);
END_VAR
VAR
    fbToCall : SomeFb;
END_VAR

fbToCall(aString:='dsfsd');

// expected
// Same as in
```

**Comment by Barteling** [comment]
Status update, I have almost finished a beta version with improvements on the function block initializers. 
I hope to have it released this weekend,

**Comment by Barteling** [comment]
I improved the formatting of function block initializers with the new release 3.0.0-Beta (both TwinCAT and Codesys version).
https://www.stweep.com/beta-releases

There are quite a lot new settings, (see changelog) I intend to add  the same settings to array initializers  
<pre>
Var : array[0..1] of FB := [(A := B, C :=D),(A := B, C :=D)]
</pre>
And struct initializers:
<pre>
Var : Struct := (A := B, C :=D)
</pre> 

Let me know your findings with this version

**Comment by RogerChristopher** [comment]
Using Stweep version 3.0.0-Beta I get
```    
RH_FlowPack_PackML_Controller : T_FlowPack_PackML_Controller(
        FlowPackXts := PB_BDFS.RH_FlowPack_XTS,
        RejectStation := PB_BDFS.RH_FlowPack_RejectStation,
        Wrapper := Wrapper,
        MasterAxis := PB_BDFS.RH_MasterAxis);
```
But with "Align similar code in columns" checked for Variable Initialisers I would expect the assignment operators to line up:
```
    RH_FlowPack_PackML_Controller : T_FlowPack_PackML_Controller(
        FlowPackXts    := PB_BDFS.RH_FlowPack_XTS,
        RejectStation  := PB_BDFS.RH_FlowPack_RejectStation,
        Wrapper        := Wrapper,
        MasterAxis     := PB_BDFS.RH_MasterAxis);
```
Similarly, with no line break after the opening parenthesis, I would expect:
```
    RH_FlowPack_PackML_Controller : T_FlowPack_PackML_Controller(FlowPackXts     := PB_BDFS.RH_FlowPack_XTS,
                                                                 RejectStation   := PB_BDFS.RH_FlowPack_RejectStation,
                                                                 Wrapper         := Wrapper,
                                                                 MasterAxis      := PB_BDFS.RH_MasterAxis);
```

**Comment by Barteling** [comment]
@RogerChristopher  could you send me you settings file?

**Comment by RogerChristopher** [comment]
Settings file attached

**Comment by Barteling** [comment]
@RogerChristopher  hmm i don't see it, can you upload it using github instead of email?

**Comment by RogerChristopher** [comment]
Attached:
[Settings.zip](https://github.com/Barteling/STweep/files/5988103/Settings.zip)

**Comment by RogerChristopher** [comment]
Note that this is using Fb_init() to initialise some interfaces, so may be different to variable initialisation.

**Comment by Barteling** [comment]
@RogerChristopher Yes this is different which is why i added a bunch of settings dedicated for function block initializers  in 3.0.0 Beta.
You need to have a look at these settings:
particularly  to:
-  Linebreaks and wrapping > Function block Initializers > Line break after '('  in function block initializers
(you have "keep existing line breaks" true, if there is a line break after "(" it will stay there regardless of this settings).
- Tabs indent and alignment > Align multiline constructs > Function block initializer parameters 
- Tabs indent and alignment > Align multiline constructs > Function block initializer parameter assignments.

Let me know if this helps you.

Red line on category is wrong in the first screen, this is "Linebreaks and wrapping" not "Blank lines"

![Screenshot 2021-02-16 123736](https://user-images.githubusercontent.com/33071638/108058445-588afe80-7054-11eb-9e07-625c6f189254.png)
![Screenshot 2021-02-16 123850](https://user-images.githubusercontent.com/33071638/108058448-59bc2b80-7054-11eb-9612-70846d3185c9.png)
![Screenshot 2021-02-16 124036](https://user-images.githubusercontent.com/33071638/108058450-59bc2b80-7054-11eb-94dc-3927c1650b20.png)
![Screenshot 2021-02-16 124713](https://user-images.githubusercontent.com/33071638/108058987-1ca46900-7055-11eb-8c21-f9f77e2a218a.png)

**Comment by RogerChristopher** [comment]
Thanks - yes this makes sense. I was confusing variable initialisation with function block initialisation
