### ISSUE TITLE
Multi-lines pragma directive

### ISSUE THREAD

**Issue by patopat** [Barteling/STweep#39]
Hi,

Pragma directive defined on multi-lines aren't handling. Could you improve it ?

**Current :**
![image](https://user-images.githubusercontent.com/20794916/114455059-9717e200-9bdb-11eb-8d9d-61322a691af1.png)

**After format code :**
![image](https://user-images.githubusercontent.com/20794916/114455334-ee1db700-9bdb-11eb-9ea7-157dfce4962e.png)

**Expected :**
![image](https://user-images.githubusercontent.com/20794916/114454254-b6623f80-9bda-11eb-8830-6522fbe81a01.png)

Best regards

**Comment by Barteling** [comment]
Currently STweep does indeed not change to content of pragmas.
I have plans for improvement of this but this is quite tricky because pragmas can literally look like anything, so where am to place my spaces and new lines? 
Of course there are certain predefined attributes I could use, to for example indent within a pragma IF.

I'm not exactly sure what you wan to see in the expected code example code, indented within the IF statement, blank line within the IF statement and a line break in the TCLinkTo attribute because it exceeds you line length overflow?

**Comment by patopat** [comment]
In my example, the TCLinkTo attribute could be view as a variable assignment, so formatting rules could be applied easily.
I think, in most cases pragma directives take place on a single line, except TCLinkTo.

And yes, indent within a pragma IF is expected, so could be a setting.

**Comment by Barteling** [comment]
Understood,
I close this issue for now but I keep this on the enhancement list.
But I'm not sure about a time path yet, i have some enhancements with an higher priority.
