### ISSUE TITLE
option to keep single line if then ... end_if

### ISSUE THREAD

**Issue by wla-git** [Barteling/STweep#44]
Can you add an option to keep the single line if then end_if?

I think line length limit should overrule this option

e.g.
IF [condition] THEN [statement] END_IF

**Comment by Barteling** [comment]
Technically I could yes. It has been requested more.
I never worked on it because the need did not seem to high, (and I personally don't like it), so it was not high on my priority list.
See also the discussion here: #15

But if you really want it i'll see what I can do. 
But I think  would prefer an option like: "Place IF statements with one statement one a single line" or something like that.
Rather then keeping existing layouts. Line lengths limits should indeed always be respected.

Would that work for you?

**Comment by wla-git** [comment]
reading the thread you noticed, i guess this was my request ;-) 
Your suggestion is "Place IF statements with one statement one a single line" is exactly the option i like to use..

when multiple statements are used, always use the standard formatting, I agree completely with the previous thread.

**Comment by Barteling** [comment]
Yes it was your request, but you we're not the only one. 

I'll put this option on my feature list, but I have yet to decide how to implement it, and I have some features with a higher priority so I don't expect it in the next few releases. 

I'll keep you up to date 👍🏼

**Comment by Barteling** [comment]
Added in 4.1.0- Beta
https://www.stweep.com/beta-releases/
