### ISSUE TITLE
Invocation call parameters assignments format not working

### ISSUE THREAD

**Issue by nbuchele-KAMP** [Barteling/STweep#56]
**Describe the bug**
The "Invocation call parameters assignments" option is not aligning assignment operators.

**Expected behavior**
I would expect the code to look like this:
![image](https://user-images.githubusercontent.com/85587088/156793624-afe5321a-ec15-48d1-b88e-ede504ec75ec.png)

However, the code is formatted to this:
![image](https://user-images.githubusercontent.com/85587088/156793274-2af644b9-106a-4ba9-bf91-60dde4de3730.png)

I have the setting enabled:
![image](https://user-images.githubusercontent.com/85587088/156793202-e45e9bda-16af-4006-a3f8-92ed17684488.png)

**STweep version info**
STweep for TwinCAT 4.0.1

**IDE version info**
 "TwinCAT XAE Shell 
![image](https://user-images.githubusercontent.com/85587088/156793966-974dd9a4-a331-4de9-8275-d128efdbea8b.png)

**Settings Export**
[STweep_settings.zip](https://github.com/Barteling/STweep/files/8187006/STweep_settings.zip)

**Comment by Barteling** [comment]
I think there is no alignment because you are using tabs for alignment.
And the difference between the variable length is not big enough for a tab. in your example you need 1 or 2 spaces for alignment.

You might want to have  at the parameter Alignment style when tabs are used. 
You currently have set this to 'Tabs' but consider "Tabs and spaces" or "all members in columns" depending on your preferences

Let me know if this solves your problem


![Untitled](https://user-images.githubusercontent.com/33071638/156796546-62c1b645-67a8-416f-8cea-bd48be931e83.png)

**Comment by nbuchele-KAMP** [comment]
I changed to the "All members in columns" and that fixed it. Thanks for the help!
